stages:
  - build
  - test

build:
  stage: build
  script:
    - apt-get update && apt-get install -y openjdk-11-jdk # Telepíti a Java JDK-t
    - javac src/**/*.java -d target/classes # Lefordítja a Java forrásfájlokat
    - jar cf target/my-app.jar -C target/classes . # Létrehozza a JAR fájlt

test:
  stage: test
  script:
    - echo "test"